table dim_vehicle
	lineageTag: c7000000-0000-4000-8000-00000000000a

	column vehicle_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		isHidden
		isKey: true
		sourceColumn: vehicle_id

	column driver_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		isHidden
		displayFolder: Keys
		sourceColumn: driver_id

	column vehicle_type
		dataType: string
		summarizeBy: none
		sourceColumn: vehicle_type

	column year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: year

	column is_deleted
		dataType: boolean
		summarizeBy: none
		displayFolder: Compliance
		sourceColumn: is_deleted

	column vehicle_type_was_normalized
		dataType: boolean
		summarizeBy: none
		displayFolder: "Data Quality"
		sourceColumn: vehicle_type_was_normalized


	partition dim_vehicle-01 = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost:5433", "mobility_dw"),
				    reporting_dim_vehicle = Source{[Schema="reporting", Item="dim_vehicle"]}[Data],
				    #"Selected Columns" = Table.SelectColumns(reporting_dim_vehicle, {"vehicle_id","driver_id","vehicle_type","year","is_deleted","vehicle_type_was_normalized"})
				in
				    #"Selected Columns"

	annotation PBI_ResultType = Table
